name = "Minecraft Mod"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "daf116efa7dac534800524b09e8b72ead3086af9fed0f11199bf64b0d58d4ad4"

[versions]
fabric = "0.18.1"
minecraft = "1.21.10"
