name = "Minecraft Mod"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b830321f868daaade0d12017a784292ac5c6d458c2e3a283c1070839defe017e"

[versions]
fabric = "0.18.1"
minecraft = "1.21.10"
