name = "Minecraft Mod"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3471ce10f43f03d34b077f59e9baf970a5256276731ebe9ed8a23e324ac2ef25"

[versions]
fabric = "0.18.1"
minecraft = "1.21.10"
